MyLunchBox/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyLunchBox.Models;
using System.Web.Security;
using MyLunchBox.Utilities;

namespace MyLunchBox.Controllers
{
    [Authorize]
    public class MemberController : Controller
    {
        private int CurrentUserId
        {
            get
            {
                return MembershipHelper.GetUserIdByEmail(HttpContext.User.Identity.Name).Value;
            }
        }
        private MyLunchBoxDevelopmentEntities db = new MyLunchBoxDevelopmentEntities();
        //
        // GET: /Member/

        public ActionResult MyLunchBoxes()
        {
            SiteMenuHelper.Instance.CurrentSiteMenu = SiteMenu.Account;
            var orders =  db.Orders.Where(i => i.UserId == CurrentUserId).OrderByDescending(i=>i.OrderReceivedAt);
            return View(orders);
        }


        public ActionResult MyPayments()
        {
            SiteMenuHelper.Instance.CurrentSiteMenu = SiteMenu.Account;
            return View();
        }

        public ActionResult MyRewards()
        {
            SiteMenuHelper.Instance.CurrentSiteMenu = SiteMenu.Account;
            var userId = MembershipHelper.GetUserIdByEmail(HttpContext.User.Identity.Name);
            var rewards = db.Rewards.Where(i=>i.UserId == userId ).OrderByDescending(i=>i.RewardCreatedAt);
            var rewardCardTypes = db.RewardCards.Select(i => new { i.RewardCardId, i.RewardDescription }).ToList().Select(i => new SelectListItem() { Text = i.RewardDescription, Value = i.RewardCardId.ToString() }).ToList();
            ViewData["rewardCardTypes"] = rewardCardTypes;
            return View(rewards);
        }

        [HttpPost]
        public ActionResult MyRewards(FormCollection values)
        {
            var rewardCardId = Convert.ToInt32(values["rewardCardTypes"]); 
            var cart = ShoppingCartHelper.GetCart(HttpContext);
            var rewardCard = db.RewardCards.Single(i=>i.RewardCardId == rewardCardId);
            cart.AddToCart(rewardCard);
            db.SaveChanges();
            return RedirectToAction("Edit", "ShoppingCart");
        }
        public ActionResult MyVotes()
        {
            SiteMenuHelper.Instance.CurrentSiteMenu = SiteMenu.Account;
            var myUniversity = LocationHelper.GetSelectedUniversityId(HttpContext);
            var restaurants = db.Restaurants.Where(i=>myUniversity.HasValue ? i.UniversityId == myUniversity.Value : true).Select(i => new { Text = i.RestaurantName, Value = i.RestaurantId }).AsEnumerable().Select(i => new SelectListItem() { Text = i.Text, Value = i.Value.ToString() }).ToList();
            var dishes = db.Restaurants.ToDictionary(i=>i.RestaurantId, v=> v.Dishes.ToList());
            var votes = new Dictionary<int, List<Voting>>();
            var votedOn = new Dictionary<int, DateTime>();
            var deadlineStart = DateTime.Now.AddDays(-(int)DateTime.Now.DayOfWeek);
            var deadlineEnd = deadlineStart.AddDays(7);
            foreach (var restaurantId in dishes.Keys)
            {
                votes.Add(restaurantId, 
                    db.Votings.Where(i => i.Dish.RestaurantId == restaurantId && i.VotedOn.CompareTo(deadlineStart) > 0 && i.VotedOn.CompareTo(deadlineEnd) < 0 && i.VotedBy == CurrentUserId)
                    .ToList());
                if (votes[restaurantId].Count() > 0)
                {
                    votedOn.Add(restaurantId, votes[restaurantId].First().VotedOn);
                }
            }
            ViewData["restaurants"] = restaurants;
            ViewData["dishes"] = dishes;
            ViewData["votes"] = votes;
            ViewData["votedOn"] = votedOn;
            var totalVotings = db.Votings.Count(c => deadlineStart.CompareTo(c.VotedOn) < 0 && c.VotedOn.CompareTo(deadlineEnd) < 0 && c.Dish.IsOnVoting == true);
            
            ViewData["votingStats"] = db.Dishes.ToDictionary(i => i.DishId, v => string.Format("{0:0.##}", 
                totalVotings == 0 ? 0 : (decimal)v.votings.Count(c => deadlineStart.CompareTo(c.VotedOn) < 0 && c.VotedOn.CompareTo(deadlineEnd) < 0 && c.Dish.IsOnVoting == true) / totalVotings * 100));

            ViewData["orderStats"] = Dish.GetDishOrderStats(deadlineStart, deadlineEnd).OrderByDescending(i=>i.Value).ToDictionary(i=>i.Key, j=>j.Value); 
            return View();
        }

        [HttpPost]
        public ActionResult MyVotes(FormCollection values)
        {
            var selectedDishes = new List<string>();

            for (int i = 0; i < values.Count; i++)
            {
                var dishId = Convert.ToInt32(values[i]);
                var dish = db.Dishes.Single(j => j.DishId == dishId);
                var voting = new Voting() { DishId = dishId, VotedOn = DateTime.Now , VotedBy= CurrentUserId};
                db.Votings.AddObject(voting);
            }

            var reward = new Reward()
            {
                RewardCreatedAt = DateTime.Now,
                RewardDescription = "Voting",
                Amount = 30,
                UserId = CurrentUserId,
                RewardTypeId = (int)RewardType.Voting
            };
            db.Rewards.AddObject(reward);

            db.SaveChanges();
            return RedirectToAction("MyVotes");
        }
        public ActionResult MembershipDetails()
        {
            SiteMenuHelper.Instance.CurrentSiteMenu = SiteMenu.Account;
            var userId = MembershipHelper.GetUserIdByEmail(HttpContext.User.Identity.Name);
            var userDetails = db.UserDetails.Single(i => i.UserId == userId);
                    
            var universities = db.Universities
                                    .Select(i => new { Text = i.UniversityName, Value = i.UniversityId }).AsEnumerable()
                                    .Select(x => new SelectListItem { Text = x.Text, Value = x.Value.ToString(), Selected = (userDetails.UniversityId.HasValue ? x.Value == userDetails.UniversityId.Value : false )}).ToList();
            var deliveryLocations = db.University_Delivery
                                    .Where(i => userDetails.UniversityId.HasValue ? i.UniversityId == userDetails.UniversityId : false)
                                    .Select(i => new { i.UniversityDeliveryId, i.Location.BusinessName, i.DeliveryTime }).AsEnumerable()
                                    .Select(i => new SelectListItem { Text = i.BusinessName + " " + i.DeliveryTime.ToString("hh:mm tt"), Value = i.UniversityDeliveryId.ToString(), Selected = userDetails.UniversityDeliveryId.HasValue? userDetails.UniversityDeliveryId.Value == i.UniversityDeliveryId : false }).ToList();

            var detailModel = new UserDetailsViewModel
            {
                FirstName = userDetails.FirstName,
                LastName = userDetails.LastName,
                PhoneNumber = userDetails.PhoneNumber,
                LocationFirstName = userDetails.Location != null ? userDetails.Location.FirstName : "",
                LocationLastName = userDetails.Location != null ? userDetails.Location.LastName : "",
                Address1 = userDetails.Location != null ? userDetails.Location.Address1 : "",
                Address2 = userDetails.Location != null ? userDetails.Location.Address2 : "",
                City = userDetails.Location != null ? userDetails.Location.City : "",
                State = userDetails.Location != null ? userDetails.Location.StateOrProvince : "",
                ZipCode = userDetails.Location != null ? userDetails.Location.ZipCode : "",
                Universities = universities,
                States = MyLunchBox.Models.StatesRepository.Instance.StatesListWithSelectedItem(userDetails.Location != null ? userDetails.Location.StateOrProvince : ""),
                DeliveryLocations = deliveryLocations,
                UniversityId = userDetails.UniversityId.HasValue ? userDetails.UniversityId.Value : -1,
                UniversityDeliveryId = userDetails.UniversityDeliveryId.HasValue ? userDetails.UniversityDeliveryId.Value : -1
            };
            return View( detailModel);
        }

        [HttpPost]
        public ActionResult MembershipDetails(FormCollection values)
        {
            var userId = MembershipHelper.GetUserIdByEmail(HttpContext.User.Identity.Name);
            var userDetails = db.UserDetails.Single(i=>i.UserId == userId);
            userDetails.FirstName = values["firstName"];
            userDetails.LastName = values["lastName"];
            userDetails.PhoneNumber = values["phoneNumber"];
            userDetails.UniversityId = Convert.ToInt32(values["UniversityId"]);
            userDetails.UniversityDeliveryId = Convert.ToInt32(values["UniversityDeliveryId"]);
            if (userDetails.Location == null)
            {
                var location = new Location()
                {
                    LocationName = values["LocationFirstName"] + values["LocationLastName"],
                    FirstName = values["LocationFirstName"],
                    LastName = values["LocationLastName"],
                    Address1 = values["Address1"],
                    Address2 = values["Address2"],
                    City = values["City"],
                    StateOrProvince = values["State"],
                    ZipCode = values["ZipCode"],
                    CountryCode = "US",
                    Country = "United States"
                };
                db.Locations.AddObject(location);
                db.SaveChanges();
                userDetails.LocationId = location.LocationId;
            }
            else
            {
                userDetails.Location.FirstName = values["LocationFirstName"];
                userDetails.Location.LastName = values["LocationLastName"];
                userDetails.Location.Address1 = values["Address1"];
                userDetails.Location.Address2 = values["Address2"];
                userDetails.Location.City = values["City"];

MyLunchBox/Views/Member/MembershipDetails.cshtml
@model MyLunchBox.Models.UserDetailsViewModel

@{
    ViewBag.Title = "MembershipDetails";
}

<div class="row">
    <div class="span3 well" style="padding:20px 0;">
    <ul class="nav nav-list">
	    <li class="nav-header">My Account</li>
	    <li class="active">@Html.ActionLink("Account Settings", "MembershipDetails", "Member")</li>
	    <li>@Html.ActionLink("Orders", "MyLunchBoxes", "Member")</li>
	    <li>@Html.ActionLink("Reward Points", "MyRewards", "Member")</li>
	    <li>@Html.ActionLink("Voting", "MyVotes", "Member")</li>
    </ul>
    </div>
    <div class="span9">
    
    <div class="lightBox form-horizontal">
    @if (!string.IsNullOrEmpty((string)ViewData["UpdateStatus"]))
    {
    <ul class="alert alert-block alert-success" ><li>@ViewBag.UpdateStatus</li></ul>
    }
    @using (Html.BeginForm())
    {
    <fieldset>
    <legend>Basic Info</legend>
    <div class="control-group">
	    <label class="control-label" for="email">Email:</label>
	    <div class="controls controlsText">
	    	@User.Identity.Name
	    </div>
    </div>
    
    <div class="control-group">
	    <label class="control-label" for="firstName">First Name:</label>
	    <div class="controls">
            @Html.EditorFor(m => m.FirstName, new { @class = "text-box single-line" })
	    </div>
    </div>
    
    <div class="control-group">
	    <label class="control-label" for="lastName">Last Name:</label>
	    <div class="controls">
	    	@Html.EditorFor(m => m.LastName, new { @class = "text-box single-line" })
	    </div>
    </div>
    
    <div class="control-group">
	    <label class="control-label" for="phone">Phone:</label>
	    <div class="controls">
	    	@Html.EditorFor(m => m.PhoneNumber, new { @class = "text-box single-line" })
            @Html.ValidationMessageFor(m=>m.PhoneNumber)
	    </div>
    </div>
    
    </fieldset>
    <legend>Delivery Info</legend>
    <div class="control-group">
	    <label class="control-label" for="UniversityId">University:</label>
	    <div class="controls">
	    	@Html.DropDownListFor(m => m.UniversityId, @Model.Universities)
	    </div>
    </div>
    <div class="control-group">
	    <label class="control-label" for="UniversityDeliveryId">Location and Time:</label>
	    <div class="controls">
	    	@Html.DropDownListFor(m => m.UniversityDeliveryId, @Model.DeliveryLocations)
	    </div>
    </div>
    <fieldset style="display:none">
    <legend>Contact Info</legend>

    <div class="control-group">
	    <label class="control-label" for="qq">QQ:</label>
	    <div class="controls">
	    	<input name="qq" id="qq" type="text" value="" />
	    </div>
    </div>
    <div class="control-group">
	    <label class="control-label" for="msn">MSN:</label>
	    <div class="controls">
	    	<input name="msn" id="msn" type="text" value="" />
	    </div>
    </div>    
    </fieldset>
    <fieldset id="billingInfo" style="display: block;">
            <legend>Address</legend>
            <div class="control-group">
            <label for="billingFirstName" class="control-label">First Name</label>
            <div class="controls">@Html.EditorFor(m => m.LocationFirstName, new { @class = "text-box single-line" })
            </div>
            </div>
            <div class="control-group">
            <label for="billingLastName" class="control-label">Last Name</label>
            <div class="controls">@Html.EditorFor(m => m.LocationLastName, new { @class = "text-box single-line" })</div>
            </div>
            <div class="control-group">
            <label for="billingAddress1" class="control-label">Address Line1</label>
            <div class="controls">@Html.EditorFor(m => m.Address1, new { @class = "text-box single-line" }) </div>
            </div>
            <div class="control-group">
            <label for="billingAddress2" class="control-label">Address Line2</label>
            <div class="controls">@Html.EditorFor(m=>m.Address2, new {@class="text-box single-line"}) </div>
            </div>
            <div class="control-group">
            <label for="billingCity" class="control-label">City</label>
            <div class="controls">@Html.EditorFor(m=>m.City, new {@class="text-box single-line"})</div>
            </div>
            <div class="control-group">
            <label for="billingState" class="control-label">State</label>
            <div class="controls">@Html.DropDownListFor(m=>m.State, @Model.States)</div>
            </div>
            <div class="control-group">
            <label for="billingZipCode" class="control-label">ZipCode</label>
            <div class="controls">
                @Html.EditorFor(m=>m.ZipCode, new {@class="text-box single-line"})
                @Html.ValidationMessageFor(m=>m.ZipCode)
            </div>
            </div>
     </fieldset>
    <div class="clearfix">
    <input type="submit" class="btn btn-primary btn-big pull-right" value="Save Changes" />
    </div>
    }
    </div>
    </div>
</div>

<script>
    $(function () {
        $("#UniversityId").change(function () {
            $.get("/Member/GetDeliveryLocations", { "universityId": $(this).val() }, function (data) {
                console.log("...");
                $("#UniversityDeliveryId").html(data)
            });
        });
    });
</script>

MyLunchBox/Views/Member/MyLunchBoxes.cshtml
@model IEnumerable<MyLunchBox.Models.Order>

@{
    ViewBag.Title = "MyLunchBoxes";
}

<div class="row">
    <div class="span3 well" style="padding:20px 0;">
    <ul class="nav nav-list">
	    <li class="nav-header">My Account</li>
	    <li>@Html.ActionLink("Account Settings", "MembershipDetails", "Member")</li>
	    <li class="active">@Html.ActionLink("Orders", "MyLunchBoxes", "Member")</li>
	    <li>@Html.ActionLink("Reward Points", "MyRewards", "Member")</li>
	    <li>@Html.ActionLink("Voting", "MyVotes", "Member")</li>
    </ul>
    </div>
    <div class="span9">
    <div class="lightBox">
        @if (Model.Count() == 0)
        {
            <h2> You haven't order anything yet, @Html.ActionLink("create one Now", "ChooseRestaurant", "CustomBentoBox")</h2>
        }
        else
        {
        	<h3>Orders</h3>
            <table class="table table-striped">
            <tr>
            <th>
            Order#
            </th>
            <th>
            Lunchboxes
            </th>
            <th>
            Delivery Info
            </th>
            <th>
            Price
            </th>
            </tr>
            @foreach (var order in Model)
            {
                <tr> 
                    <td class="">
                    	<em>#@order.OrderId</em>
                        <p class="orderTime">@order.OrderReceivedAt.ToString("MMM dd, yyyy hh:mm")</p>
                    </td> 
                    <td>
                    	<p class="orderRestaurant"> 
                            @order.ShortDescription
                        </p>
                        <ul class="orderItems">
                            @foreach (var orderItem in order.OrderItems)
                            {
                                <li>
                                 <span class="orderItems-desc">@orderItem.Item.ItemDescription</span>  
                                 <span class="orderItems-qty">x @orderItem.Quantity</span>
                                
                                  (<a href='@orderItem.EditUrl'> edit </a>)
                                </li>
                            }
                        </ul>
                        <a  href="/ShoppingCart/Edit?orderId=@order.OrderId"><i class="icon-plus icon-orange"></i>Reorder </a>
 					<td class="orderDelivery">
                        @if( order.NeedDeliveryInfo != null ) {
                            @order.ReceiverFirstName <text></text> @order.ReceiverLastName <br />
                            <text>Phone :</text> @order.ReceiverPhoneNumber <br/>
                            @order.DeliveryLocation.BusinessName <text></text>
                            if (order.DeliveryLocation.University_Delivery.Count > 0)
                            {
                                @order.DeliveryLocation.University_Delivery.First().DeliveryTime.ToString("hh:mm tt")
                            }
                            <br />
                            @order.OrderReceivedAt.ToString("MMM dd, yyyy") 
                        }
                    
                    </td> 
                    <td class="orderPrice">
                    <br />
                    @if (!string.IsNullOrEmpty(@order.TxnId))
                    {
                        <span class="label label-success">Credit Card Paid：<br />$@(order.Gross - order.Savings) </span>
                    }
                    else if (order.Gross > order.Savings)
                    {
                        <span class="label label-warning">Cash ：<br /><big>$@(order.Gross - order.Savings)</big> </span>
                    }
                    @if (@order.Savings > 0)
                    {
                        <span class="label label-info">Points Paid:<br />$@order.Savings</span>
                    }
                    
                    </td>
 
                   
                </tr>
            }
            </table>
        }
    </div>
    </div>
</div>

MyLunchBox/Views/Member/MyRewards.cshtml
@model IEnumerable<MyLunchBox.Models.Reward>

@{
    ViewBag.Title = "MyRewards";
}
<script>
$(function(){
	$('#rewardCardTypes').change(function() {
		var selected = $(this).find('option:selected').val();
		var discount = 'Sells for $20.00 - Save <em>5%</em>';
		switch(selected) {
			case '3':
			discount = 'Sells for $50.00 - Save <em>10%</em>';
			break;
			case '4':
			discount = 'Sells for $100.00 - Save <em>$20.00</em> <big>!</big>';
			break;
		}
		$('#rewardDiscount').html(discount);
	});
});
</script>
<div class="row">
    <div class="span3 well" style="padding:20px 0">
    <ul class="nav nav-list">
	    <li class="nav-header">My Account</li>
	    <li>@Html.ActionLink("Account Settings", "MembershipDetails", "Member")</li>
	    <li>@Html.ActionLink("Orders", "MyLunchBoxes", "Member")</li>
	    <li class="active">@Html.ActionLink("Reward Points", "MyRewards", "Member")</li>
	    <li>@Html.ActionLink("Voting", "MyVotes", "Member")</li>
    </ul>
    </div>

    <div class="span9">
    <div class="lightBox">
    <h3>Reward Points</h3>
    <table class="table">
        <tr>
            <td><i class="icon-gift icon-orange"></i><br />Get more points </td>
            <td>
                @using(Html.BeginForm()) {
                    @Html.DropDownList("rewardCardTypes") <br />
                    <p id="rewardDiscount">Sells for $20.00 - Save <em>5%</em></p>
                    <input type="submit" value="Buy Card Now" class="btn" />
                } 
            </td>
        </tr>
	    <tr>
		    <td>Balance</td><td><em>@Model.Sum(i => i.Amount).ToString()</em></td>
	    </tr>
	    <tr>
		    <td>Awarded</td><td>@Model.Where(i => i.RewardTypeId == (int)MyLunchBox.Models.RewardType.LuckySpin).Sum(i => i.Amount).ToString("+#;-#;0")</td>
	    </tr>
	    <tr>
		    <td>Bought</td><td>@Model.Where(i => i.RewardTypeId == (int)MyLunchBox.Models.RewardType.RewardCard).Sum(i => i.Amount).ToString("+#;-#;0")</td>
	    </tr>
	    <tr>
		    <td>Used</td><td>@Model.Where(i => i.RewardTypeId == (int)MyLunchBox.Models.RewardType.Order).Sum(i => i.Amount).ToString("+#;-#;0")</td>
	    </tr>
    </table>
    
    @if (Model.Count() == 0)
    {
        <h2>You haven't got any reward point record yet</h2>
    }
    else
    {
    <table class="table table-hover table-condensed">
    <tr>
        <th> Time </th>
        <th> Points</th>
        <th> Description</th>
        <th> Code</th>
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        <td class="orderTime">
            @Html.DisplayFor(modelItem => item.WeekSpan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RewardDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RewardId)
        </td>
    </tr>
    }
    </table>
    }
    </div>
    </div>
</div>

MyLunchBox/Views/Member/MyVotes.cshtml
@model MyLunchBox.Models.Voting

@{
    ViewBag.Title = "MyVotes";
    var restaurants = (IEnumerable<SelectListItem>)ViewData["restaurants"];
    var restaurantVotings = (Dictionary<int, DateTime>)ViewData["votedOn"];
    var restaurantDishes = (Dictionary<int, List<MyLunchBox.Models.Dish>>)ViewData["dishes"];
}

<div class="row">
    <div class="span3 well" style="padding:20px 0">
    <ul class="nav nav-list">
	    <li class="nav-header">My Account</li>
	    <li>@Html.ActionLink("Account Settings", "MembershipDetails", "Member")</li>
	    <li>@Html.ActionLink("Orders", "MyLunchBoxes", "Member")</li>
	    <li>@Html.ActionLink("Reward Points", "MyRewards", "Member")</li>
	    <li class="active">@Html.ActionLink("Voting", "MyVotes", "Member")</li>
    </ul>
    </div>

    <div class="span9">
        <ul class="nav nav-tabs nav-tabs-small" id="fillLunchboxTab">
            @foreach (var restaurant in restaurants)
            {
                <li class="@if (restaurant.Value == restaurants.First().Value)
                           {  <text>active</text> }"><a href="#restaurant-@restaurant.Value" data-toggle="tab">@restaurant.Text</a> </li>
            }
			</ul>
        <div class="tab-content lightBox">
           @foreach (var dishes in restaurantDishes)
           {
                <div class="tab-pane @if (dishes.Key == Convert.ToInt32(restaurants.First().Value))
                                     {  <text>active</text> }" id="restaurant-@dishes.Key">
                @using (Html.BeginForm())
                {
                	<h3>Vote for Next Week's Menu</h3>
                    DateTime? votedOn = null;
                    if (restaurantVotings.ContainsKey(dishes.Key))
                    {
                        votedOn = ((Dictionary<int, DateTime>)ViewData["votedOn"])[dishes.Key];
                    }
                    var votingStats = (Dictionary<int, string>)ViewData["votingStats"];
                    var orderStats = (Dictionary<int, int>)ViewData["orderStats"];
                    if (votedOn.HasValue)
                    {  <ul id="warningMsg" class="alert alert-block alert-success" style=""><li>@string.Format("You have voted on {0:MMM dd, yyyy hh:mm:ss}", votedOn)</li>
         <li>You've got <em>30</em> reward points for this vote!</li>        
                    </ul>
                    }
                    <p>排名第一的将会出现在下周的菜单中。</p>
                    <table class="table table-striped">
                        @foreach (var dish in @dishes.Value.Where(i=>i.IsOnVoting == true))
                        {
                        if (dish.DishTypeId == (int)MyLunchBox.Models.DishType.MainCourse)
                        {
                            <tr>
                                <td class="voteCheckbox"><input type="checkbox" name="@dish.DishId" value="@dish.DishId" id="dish-@dish.DishId" 
                                @if (((Dictionary<int, List<MyLunchBox.Models.Voting>>)ViewData["votes"])[@dishes.Key].Count(j => j.DishId == dish.DishId) > 0)
                                {<text>checked=checked</text>} 
                                @if (votedOn.HasValue){ <text>disabled="disabled"</text>} />
                                </td>
                                <td class="voteImg"><img src="/@dish.DishImageUrl" width="40px" /></td>
                                <td class="voteText">@dish.DishName</td>
                                <td class="voteStat">
                                @if (votedOn.HasValue)
                                {
                                    if (votingStats.ContainsKey(@dish.DishId))
                                    {
                                    <div class="progress progress-success progress-striped" >
                                      <div class="bar" style="width:@votingStats[@dish.DishId]%"></div><span class="voteStatText">@votingStats[@dish.DishId]%</span>
                                    </div>
                                        
                                    }
                                }
                                </td>
                            </tr>
                        }
                             
                        }
                    </table>
                    <input type="submit" value="Vote" class="btn" @if (votedOn.HasValue)
                                                                  { <text>style="display:none;"</text>} />   
                	
                	<hr />
                	<h3>Current Menu</h3>
                    <p>The least popular dish will be removed from next week's menu!</p>
                	<table class="table table-striped current-menu" >
                		<tr>
                		<th class="voteRank">
                		Rank
                		</th>
                		<th>
                		</th>
                		<th>
                		Dishes
                		</th>
                		<th>
                		Popularity
                		</th>
                		</tr>
                        @{var rank = 1;}
                        @foreach( var dishId in @orderStats.Keys)
                        {
                            if (votedOn.HasValue)
                            {
                                if (dishes.Value.Count(i=>i.DishId == dishId) > 0 )
                                {
                                        
                                    var dish = dishes.Value.Single(i=>i.DishId == dishId);
                                    if (dish.DishTypeId == (int)MyLunchBox.Models.DishType.MainCourse)
                                    {
                                    <tr>
                                    <td class="voteRank">No. <em>@rank</em>
                                    </td>
                                    <td class="voteImg"><img src="/@dish.DishImageUrl" width="40px" /></td>
                                    <td class="voteText">@dish.DishName</td>
                                    <td class="voteStat">
                                        <div class="progress progress-success progress-striped" >
                                            <div class="bar" style="width:@orderStats[@dish.DishId]%"></div><span class="voteStatText">@orderStats[@dish.DishId]</span>
                                        </div>
                                    </td>
                                    </tr>
                                        rank += 1;
                                    }
                                }
                            }
                        }
                    </table>
                }
                
                </div>
            }
            
		</div>
    </div>
</div>