MyLunchBox/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyLunchBox.Models;
using PayPal.PayPalAPIInterfaceService.Model;
using PayPal.PayPalAPIInterfaceService;
using MyLunchBox.Utilities;

namespace MyLunchBox.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        private MyLunchBoxDevelopmentEntities db = new MyLunchBoxDevelopmentEntities();

        public ActionResult AddressAndPayment()
        {
            try
            {
                var cart = ShoppingCartHelper.GetCart(HttpContext);
                if (cart.ShoppingCartItems.Count() == 0)
                {
                    return RedirectToAction("Edit", "ShoppingCart");
                }
                ViewData["cart"] = cart;
                var deliveryLocation = LocationHelper.GetDeliveryLocation(HttpContext);
                if (deliveryLocation == null)
                {
                    deliveryLocation = db.University_Delivery.First(i => i.UniversityId == 1);
                    LocationHelper.SetDeliveryLocation(HttpContext, deliveryLocation);
                }
                ViewData["deliveryLocation"] = deliveryLocation;
                DateTime deliveryTime;
                if (deliveryLocation.DeliveryTime.Hour < DateTime.Now.Hour)
                {
                    deliveryTime = DateTime.Now.Date.AddDays(1).AddHours(deliveryLocation.DeliveryTime.Hour);
                }
                else
                {
                    deliveryTime = DateTime.Now.Date.AddHours(deliveryLocation.DeliveryTime.Hour);
                }
                ViewData["deliveryTime"] = deliveryTime;
                var currentUserId = MembershipHelper.GetUserIdByEmail(HttpContext.User.Identity.Name);
                var totalRewardPoints = 0.0m;
                var pts = db.Rewards.Where(i => i.UserId == currentUserId).Sum(i => (decimal?)i.Amount);
                if (pts.HasValue)
                {
                    totalRewardPoints = pts.Value;
                }
                ViewData["totalRewardPoints"] = Convert.ToInt32(totalRewardPoints);
                var order = new Order();
                var userId = MembershipHelper.GetUserIdByEmail(HttpContext.User.Identity.Name);
                var payer = (MyLunchBoxMembershipUser)(new MyLunchBoxMembershipProvider().GetUser(User.Identity.Name, true));
                    
                order.UserId = userId.Value;
                order.OrderReceivedAt = DateTime.Now;
                order.PayerEmail = User.Identity.Name;
                order.Fee = 0.0m;
                order.Gross = cart.ShoppingCartItems.Sum(i => i.LineItemCost);
                //todo: change after add reword points
                if (cart.CanUserRewardPoint )
                {
                    order.rewardPoints = Convert.ToInt32(order.Gross * 100);
                }
                else {
                    order.rewardPoints = 0; 
                }
                order.Savings = order.rewardPoints / 100.0m;
                order.OrderDescription = string.Join(",", cart.ShoppingCartItems.Select(i => i.Description).ToList());
                order.Tax = 0.0m;
                order.PaymentType = PaymentType.NotRequired;
                    
                order.billingFirstName = payer.UserDetails.FirstName;
                order.billingLastName = payer.UserDetails.LastName;
                order.NeedDeliveryInfo = cart.NeedDeliveryInfo;
                if (cart.NeedDeliveryInfo)
                {
                    order.ReceiverFirstName = payer.UserDetails.FirstName;
                    order.ReceiverLastName = payer.UserDetails.LastName;
                    order.ReceiverPhoneNumber = payer.UserDetails.PhoneNumber;
                    order.DeliveryTime = deliveryTime;
                }
                var billingLocation = payer.UserDetails.Location;
                order.billingFirstName = billingLocation != null ? billingLocation.FirstName : "";
                order.billingLastName = billingLocation != null ? billingLocation.LastName : "";
                order.billingAddress1 = billingLocation != null ? billingLocation.Address1 : "";
                order.billingAddress2 = billingLocation != null ? billingLocation.Address2 : "";
                order.billingCity = billingLocation != null ? billingLocation.City : "";
                order.billingState = billingLocation != null ? billingLocation.StateOrProvince : "";
                order.billingZipCode = billingLocation != null ? billingLocation.ZipCode : "";
                return View(order);
                
            }
            catch
            {
                return HttpNotFound();
            }
            
        }

        public ActionResult PaymentComplete(int orderId)
        {
            var order = db.Orders.Single(i => i.OrderId == orderId);
            if (order == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(order);
            }
        }

        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            // fill out basic info
            var cart = ShoppingCartHelper.GetCart(HttpContext);
            ViewData["cart"] = cart;
            var deliveryLocation = LocationHelper.GetDeliveryLocation(HttpContext);
            if (deliveryLocation == null)
            {
                deliveryLocation = db.University_Delivery.First(i => i.UniversityId == 1);
                LocationHelper.SetDeliveryLocation(HttpContext, deliveryLocation);
            }
            ViewData["deliveryLocation"] = deliveryLocation;
            DateTime deliveryTime;
            if (deliveryLocation.DeliveryTime.Hour < DateTime.Now.Hour)
            {
                deliveryTime = DateTime.Now.Date.AddDays(1).AddHours(deliveryLocation.DeliveryTime.Hour);
            }
            else
            {
                deliveryTime = DateTime.Now.Date.AddHours(deliveryLocation.DeliveryTime.Hour);
            }
            ViewData["deliveryTime"] = deliveryTime;
            var totalRewardPoints = db.Rewards.Sum(i => i.Amount);
            ViewData["totalRewardPoints"] = totalRewardPoints;

            //fillout order
            var order = new Order();
            var userId = MembershipHelper.GetUserIdByEmail(HttpContext.User.Identity.Name);
            order.Gross = cart.Gross;
            if (cart.CanUserRewardPoint)
            {
                order.rewardPoints = Convert.ToInt32(values["rewardPoints"]);
            }
            else
            {
                order.rewardPoints = 0;
            }
            order.Savings = order.rewardPoints / 100.0m;
            order.Tax = 0.0m;
            order.Fee = 0.0m;
            order.billingFirstName = values["billingFirstName"];
            order.billingLastName = values["billingLastName"];
            order.billingAddress1 = values["billingAddress1"];
            order.billingAddress2 = values["billingAddress2"];
            order.billingCity = values["billingCity"];
            order.billingState = values["billingState"];
            order.billingZipCode = values["billingZipCode"];
            order.PaymentType = (PaymentType)Enum.Parse(typeof(PaymentType), values["paymentType"]);
            order.cardNumber = values["cardNumber"];
            order.cardExpYear = int.Parse(values["cardExpYear"]);
            order.cardExpMonth = int.Parse(values["cardExpMonth"]);
            order.CSV = values["CSV"];
            order.NeedDeliveryInfo = cart.NeedDeliveryInfo;
            if (cart.NeedDeliveryInfo)
            {
                order.ReceiverFirstName = values["ReceiverFirstName"];
                order.ReceiverLastName = values["ReceiverLastName"];
                order.ReceiverPhoneNumber = values["ReceiverPhoneNumber"];
                order.DeliveryTime = deliveryTime;
            }
            order.PayerEmail = HttpContext.User.Identity.Name;
            order.UserId = userId.Value;
            order.PayerEmail = User.Identity.Name;
            order.OrderDescription = string.Join(",", cart.ShoppingCartItems.Select(i => i.Description).ToList());
            order.DeliveryLocationId = deliveryLocation.LocationId;
            PaymentStatusLevel paymentStatus = PaymentStatusLevel.WaitingForPayment;
            DeliveryInfo deliveryInfo = new DeliveryInfo() { ReceiverFirstName = order.ReceiverFirstName, ReceiverLastName = order.ReceiverLastName };

            if (!TryValidateModel(order))
            {
                return View("AddressAndPayment", "_CheckoutMaster", order);
            }
            else
            {

                if (order.PaymentType == PaymentType.CreditCard)
                {

                    DoDirectPaymentRequestType request = new DoDirectPaymentRequestType();
                    DoDirectPaymentRequestDetailsType requestDetails = new DoDirectPaymentRequestDetailsType();
                    request.DoDirectPaymentRequestDetails = requestDetails;
                    requestDetails.PaymentAction = PaymentActionCodeType.SALE;

                    // Populate card requestDetails
                    CreditCardDetailsType creditCard = new CreditCardDetailsType();
                    requestDetails.CreditCard = creditCard;
                    PayerInfoType payer = new PayerInfoType();
                    PersonNameType name = new PersonNameType();
                    name.FirstName = order.billingFirstName;
                    name.LastName = order.billingLastName;
                    payer.PayerName = name;
                    creditCard.CardOwner = payer;

                    creditCard.CreditCardNumber = order.cardNumber;
                    creditCard.CreditCardType = (CreditCardTypeType)
                        Enum.Parse(typeof(CreditCardTypeType), values["creditCardType"]);
                    creditCard.CVV2 = order.CSV;

MyLunchBox/Views/Mobile/Cart.cshtml
@model MyLunchBox.Models.ShoppingCart
@{
    ViewBag.Title = "Cart";
    Layout = "~/Views/Shared/_MobileMaster.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        bindRemove();

        $(".cart-quantity").change(function () {
            var ipt = $(this);
            var qty = parseInt(ipt.val());

            if (qty < 1) {
                ipt.val(1);
                qty = 1;
            }
            var itemId = ipt.attr('data-itemId');
            var itemTypeId = ipt.attr('data-itemTypeId');
            $.post("/ShoppingCart/ChangeQuantity/", { "itemId": itemId, "itemTypeId": itemTypeId, "quantity": qty },
        		function (data) {
        		    var tr = $("tr[data-itemId='" + itemId + "']");
        		    var unitPrice = parseFloat(tr.find('.cart-unitPrice').attr('data-price'));

        		    var totalPrice = Math.round(unitPrice * qty * 100) / 100;
        		    tr.find('.cart-totalPrice').html('$' + totalPrice);

        		    setSubtotalPrice(data.gross);

        		});

        });

        $('.btn-submit').click(function (e) {
            e.preventDefault();
            $(this).attr('disabled', 'true');

            $('<div style="position:fixed;left:0;top:0;padding-top:20%;height:80%;width:100%;background-color:rgba(0,0,0,0.6);color:#FFF;z-index:999;text-align:center;display:none"><img src="../../Content/Images/ajax-loader.gif" style="vertical-align:top" /> Processing...</div>').appendTo($('.page')).fadeIn();

            window.location.href = $(this).attr('href');

        });
    });

    function setSubtotalPrice(price) {
        $('.cart-subtotalPrice').html('$' + price);
    }

    function bindRemove() {
        $(".removeItem").click(function () {
            var itemId = $(this).attr("data-itemId");
            var itemTypeId = $(this).attr('data-itemTypeId');
            if (itemId != '') {
                $.post("/ShoppingCart/RemoveItem/", { "itemId": itemId, "itemTypeId": itemTypeId },
                    function (data) {
                        setSubtotalPrice(data.gross);
                        window.location.reload();
                    });
            }
        });
    }
</script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <ul id="steps" class="container clearfix">
        <li class="step-past"><i class="ic-number">1</i> choose a restaurant</li>
        <li class="step-past"><i class="ic-number">2</i> Choose a lunchbox</li>
        <li class="step-past"><i class="ic-number">3</i> fill my lunchbox</li>
        <li class="step-current"><i class="ic-number">4</i> check out</li>
    </ul>
    <div class="lightBox">
    <fieldset>
        <legend><h2>My Shopping Cart</h2></legend>
        <div style="display:none;">
        	@Html.HiddenFor(model => model.ShoppingCartId)
            @Html.LabelFor(model => model.UserId)
            @Html.EditorFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>
        <table id="shoppingCartItems" class="table">
            @if (Model.ShoppingCartItems.Count == 0)
            {
                <tr><td><img src="../Content/Images/emptybox.png" /></td>
                <td><div style="padding-top:50px;">Your Cart is empty! Go @Html.ActionLink("create a lunchbox", "ChooseRestaurant", "CustomBentoBox", new Object{}, new { @class = "em"} ) now!</div></td></tr>
            }
            else {
            	<tr>
            	<th></th>
            	<th>Lunchbox</th>
            	<th>Details</th>
            	<th>Unit Price</th>
            	<th>Quantity</th>
            	<th>Total Price</th>
            	<th></th>
            	</tr>
                foreach (var shoppingCartItem in Model.ShoppingCartItems)
                {
                    <tr data-itemId='@shoppingCartItem.ItemId' data-itemTypeId='@shoppingCartItem.ItemTypeId'>
                        <td>
                            <a class="removeItem delete-link" href="javascript:void(0)" data-itemId='@shoppingCartItem.ItemId' data-itemTypeId='@shoppingCartItem.ItemTypeId'><i class="icon-trash icon-brown"></i> delete</a>
                        </td>
                        <td>
                            @if(@shoppingCartItem.ItemTypeId == (int)MyLunchBox.Models.ItemType.CustomBentoBox) {
                                <p class="cart-boxName">@shoppingCartItem.CustomBentoBox.CustomBentoBoxName</p>
                                <p class="cart-boxType">@shoppingCartItem.CustomBentoBox.BentoBox.BentoBoxName </p>
                            }
                            else {
                                <p>@shoppingCartItem.Description</p>    
                            }
                        </td> 
                        <td>
                            @if( shoppingCartItem.ItemTypeId == (int)MyLunchBox.Models.ItemType.CustomBentoBox) {
                                <ul class="cart-dishList">
                                @foreach(var customItem in shoppingCartItem.CustomBentoBox.CustomBentoBoxItems) {
                                    <li> <img src="/@customItem.Dish.DishImageUrl" style="width:30px"/> <span>@customItem.Dish.DishName
                                
	                            @if (true) {
	                           		<text> x @customItem.Quantity </text> 
	                            }
                                    </span> </li>
                                }
                                </ul>
                            }
                            
                        </td>
                        <td class="cart-unitPrice" data-price="@shoppingCartItem.LineItemCost">
	                     $@shoppingCartItem.UnitPrice
                        </td>
                        <td>
	                      <input value="@shoppingCartItem.Quantity" type="number" class="input-mini cart-quantity" data-itemId='@shoppingCartItem.ItemId' data-itemTypeId='@shoppingCartItem.ItemTypeId' />
                        </td>
                        <td class="cart-totalPrice">
                        $@shoppingCartItem.LineItemCost
                        </td>
                        <td>
                        	<i class="icon-pencil icon-brown"></i> 
                            @Html.ActionLink("edit", "Create", "CustomBentoBox",  new { customBentoBoxId = @shoppingCartItem.ItemId }, new {@class="edit-link"} )
                        </td> 
                    
                        </tr>
                }
                            <tr><td colspan="5" class="cart-subtotal"><div class="pull-right">Subtotal</div></td><td class="cart-subtotalPrice big"> $@Model.Gross</td><td></td></tr>
            }

        </table>

       
    </fieldset>
    
    </div>
}

<div class="clearfix">
@if (Model.ShoppingCartItems.Count > 0) {
    @Html.ActionLink("Continue Shopping", "ChooseRestaurant", "Mobile",new object { },
new { @class = "btn pull-left"})
    @Html.ActionLink("Checkout »", "Checkout", "Mobile", new object { },
new { @class = "btn btn-primary pull-right btn-big btn-submit"})
}
</div>

MyLunchBox/Views/Mobile/CheckoutComplete.cshtml
@{
    ViewBag.Title = "CheckoutComplete";
    Layout = "~/Views/Shared/_MobileMaster.cshtml";
}

<h2>CheckoutComplete</h2>

MyLunchBox/Views/Mobile/ChooseBentoBox.cshtml
@model IEnumerable<MyLunchBox.Models.BentoBox>
           
@{
    ViewBag.Title = "ChooseBentoBox";
    Layout = "~/Views/Shared/_MobileMaster.cshtml";
}

<h2>ChooseBentoBox</h2>

<ul id="steps" class="container clearfix">
    <li class="step-past"><i class="ic-number">1</i>@Html.ActionLink("choose a restaurant", "ChooseRestaurant")</li>
    <li class="step-current"><i class="ic-number">2</i> choose a lunchbox</li>
    <li><i class="ic-number">3</i> fill my lunchbox</li>
    <li><i class="ic-number">4</i> check out</li>
</ul>
<div class="container">
    <div class="row">
    <div class="span9">
    <div class="lightBox">
    <h2>Choose a Lunchbox</h2>
    <ul id="lunchboxList" data-role="listview"  class="clearfix">
        @foreach (var bentoBox in Model)
        {
            <li class="lunchboxItem">
                
                <div class="ic-lunchbox entree-@bentoBox.NumOfEntree" >
                    <div class="lunchbox-entreeName">@bentoBox.BentoBoxName</div>
                </div>
                <div class="lunchbox-Price">$@bentoBox.UnitPrice.ToString("F02").Substring(0, bentoBox.UnitPrice.ToString("F02").IndexOf("."))<small>@bentoBox.UnitPrice.ToString("F02").Substring(bentoBox.UnitPrice.ToString("F02").IndexOf("."))</small></div>
                @Html.ActionLink("Select", "Create", new { bentoBoxId = bentoBox.BentoBoxId})
            </li>
        }
    </ul>
    
    </div>
    </div>
</div>

</div>

MyLunchBox/Views/Mobile/ChooseRestaurant.cshtml
@model IEnumerable<MyLunchBox.Models.Restaurant>
@{
    ViewBag.Title = "ChooseRestaurant";
    Layout = "~/Views/Shared/_MobileMemberMaster.cshtml";
}
<div data-role="content">
<h3>ChooseRestaurant</h3>
	<ul data-role="listview">
            @foreach (var restaurant in Model)
            {
                if ( (restaurant.RestaurantStatus == MyLunchBox.Models.RestaurantStatusLevel.Opening))
                {
                <li>
                	<a href="/mobile/ChooseBentoBox?restaurantId=@restaurant.RestaurantId">
                    	@if ( string.IsNullOrEmpty(restaurant.RestaurantImageUrl) ) {
                        <img src="/Content/Images/Restaurants/restaurantDefault.png" />
                        } else {
                        <img src="@restaurant.RestaurantImageUrl" />
                        }
                        <h3>@restaurant.RestaurantName</h3>
		                <p class="restaurant-time">@restaurant.RestaurantHoursString <span>|</span> Monday - Friday</p>
                        <p>@restaurant.RestaurantShortDescription</p>
                    </a>
                 </li>
                }
                else
                {
                	<li data-theme="d">
                    	@if ( string.IsNullOrEmpty(restaurant.RestaurantImageUrl) ) {
                        <img src="/Content/Images/Restaurants/restaurantDefault.png" />
                        } else {
                        <img src="@restaurant.RestaurantImageUrl" />
                        }
                        <h3>@restaurant.RestaurantName</h3>
		                <p class="restaurant-time">@restaurant.RestaurantHoursString <span>|</span> Monday - Friday</p>
                        <p>@restaurant.RestaurantShortDescription</p>
                        <p>@restaurant.RestaurantStatus.ToString()</p>
                    </li>
                }
                
            }
            </ul>
</div>

MyLunchBox/Views/Mobile/Index.cshtml
@{
    ViewBag.Title = "Home Impression Chinese Food";
    Layout = "~/Views/Shared/_MobileMaster.cshtml";
}


  
  <div data-role="content">
  <div style="text-align:center">
  	<img class="responsiveImg" src="/Content/Images/home.png">
  </div>

    <form action="SelectUniversity/" method="post" data-theme="c">
    <fieldset>
        <label for="username" class="ui-hidden-accessible">Email:</label>
        <input type="text" name="username" id="username" value="" placeholder="Email"/>
        <label for="password" class="ui-hidden-accessible">Password:</label>
        <input type="password" name="password" id="password" value="" placeholder="Password"/>
        <div class="ui-grid-a">
            <div class="ui-block-a">
            <input type="submit" value="Log In" data-theme="b" />
            </div>
            <div class="ui-block-b">
            <a href="SelectUniversity/" data-role="button" data-theme="d">Regiest</a>
            </div>
        </div>
    </fieldset>
    </form>
     
  </div>
  <!-- /content -->

<div data-role="footer" data-position="fixed">
    <div data-role="navbar">
		<ul>
			<li><a href="a.html" data-theme="b">400(817-6363)</a></li>
			<li><a href="b.html" data-theme="b">View Full Website</a></li>
		</ul>
	</div><!-- /navbar -->
</div> 

MyLunchBox/Views/Mobile/SelectUniversity.cshtml
@model IEnumerable<MyLunchBox.Models.University>

@{
    ViewBag.Title = "Select University";
    Layout = "~/Views/Shared/_MobileMemberMaster.cshtml";
}

<div data-role="content">
    <label for="universitySelect" class="select">Your University:</label>
    <select name="universitySelect" id="universitySelect">
        @foreach(var university in Model) 
        {
        <option value="@university.UniversityId">@university.UniversityName</option>
        }
    </select>
    @Html.ActionLink("Next", "ChooseRestaurant", new { universityId = "1"},new { data_role = "button", data_ajax="false", data_theme="b",data_icon="arrow-r",data_iconpos="right"} )
</div>